### ISSUE TITLE
如果设置滚动条，滚动条会出现错乱

### ISSUE THREAD

**Issue by xuwj** [Aspsine/IRecyclerView#13]

**Comment by Aspsine** [comment]
RecyclerView滚动条的绘制逻辑在IRecyclerView中没有做干预。

IRecyclerView的refresh header是通过设置RecycelerView position = 0 这个view的height来实现的。所以，在下拉刷新的过程中，滚动条的绘制会按照position = 0这个view的位置和大小去绘制。这个过程中会造成你描述的`错乱`。实际更准确一点描述是`跳动`。

在普通的滚动过程中，滚动条应该不会`错乱`.

要修复上述问题需要在IRecyclerView中干预RecyclerView的滚动条绘制逻辑，目前暂不作处理。

**Comment by xuwj** [comment]
恩 知道这个 只要设置了refresh header就会造成这个问题。初始显示滚动条也没位于顶部，这个确实要在IRecyclerView做干预才行  争取早日完善。

**Comment by Fan-Dev** [comment]
怎么干预，有思路吗？ @xuwj @Aspsine  可别告诉了全世界，这问题有解，但是不说方案。

**Comment by SuperZhouyong** [comment]
@Aspsine  大神还是处理下吧，我们也不会处理的哦！！
