### ISSUE TITLE
不能设置子项的点击事件

### ISSUE THREAD

**Issue by realicing** [Aspsine/IRecyclerView#15]
没有setOnItemClickListener方法

**Comment by Aspsine** [comment]
针对RecyclerView是否应该提供setOnItemClickListener，请咨询google工程师。

请参考demo设置点击监听。

https://github.com/Aspsine/IRecyclerView/blob/master/app/src/main/java/com/aspsine/irecyclerview/demo/ui/adapter/ImageAdapter.java#L30
