### ISSUE TITLE
可否客製化loadmore的位置

### ISSUE THREAD

**Issue by hsandyque** [Aspsine/IRecyclerView#17]
目前都是滑到底才會loadmore, 是否可以增加客製化的選項，譬如在滑到底的前十個load或是讓我們可以設定或覆寫OnLoadMoreScrollListener，謝謝

**Comment by Aspsine** [comment]
需要自己修改：
https://github.com/Aspsine/IRecyclerView/blob/master/library/src/main/java/com/aspsine/irecyclerview/OnLoadMoreScrollListener.java
来完成需求。
