### ISSUE TITLE
调用notifyItemRemoved(position)和notifyItemRangeChanged(position, memoList.size())后position仍然不正确

### ISSUE THREAD

**Issue by LiuZaiJun** [Aspsine/IRecyclerView#18]
WrapperAdapter中的getItemViewType方法抛出异常
throw new IllegalArgumentException("Wrong type! Position = " + position)
这个该怎么解决

**Comment by Aspsine** [comment]
``` java
ImageAdapter mAdapter = new ImageAdapter();
iRecyclerView.setIAdapter(mAdapter);
mAdapter.notify...
```

``` java
// or you need get your adapter from iRecyclerview
mAdapter = iRecyclerView.getIAdapter();
mAdapter.notify...
```

调用者一般来说不用关心WrapperAdapter, 只需要调用自定义的adapter的notify系列方法。
如果你需要`recyclerview.getAdapter()`(这里获取到的是WrapperAdapter)获取到adapter，
请使用`recyclerview.getIAdapter()`获取到获取你自己定义的adapter，然后再调用notify系列方法。

**Comment by LiuZaiJun** [comment]
非常感谢，使用getIAdapter再去notify系列方法后，position是正确的，但是仍然出现了问题，剩余2个去remove的时候，出现java.lang.IllegalArgumentException: Wrong type! Position = 5 at com.aspsine.irecyclerview.WrapperAdapter.getItemViewType

**Comment by Aspsine** [comment]
已修复，请升级：

```
compile 'com.github.Aspsine:IRecyclerView:0.0.4'
```
