### ISSUE TITLE
为什么android studio 编译不下来

### ISSUE THREAD

**Issue by codesdt** [Aspsine/IRecyclerView#22]
Error:(25, 13) Failed to resolve: com.github.Aspsine:IRecyclerView:0.0.5
<a href="openFile:/Users/huaming/Desktop/Refresh/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Aspsine** [comment]
Step 1. Add the JitPack repository to your build file. Add it in your root build.gradle at the end of repositories:

```
allprojects {
    repositories {
        ...
        maven { url "https://jitpack.io" }
    }
}
```

Step 2. Add the dependency

```
dependencies {
    compile 'com.github.Aspsine:IRecyclerView:0.0.5'
}
```
