### ISSUE TITLE
Failed to resolve: com.github.Aspsine:IRecyclerView:0.0.2

### ISSUE THREAD

**Issue by twiceyuan** [Aspsine/IRecyclerView#3]

**Comment by Aspsine** [comment]
It's maybe a bug of jitpack.
I had already post the issue to jitpack.
https://github.com/jitpack/jitpack.io/issues/539

You can check out [app module](https://github.com/Aspsine/IRecyclerView/tree/master/app) and use _Module dependence_ current now and change to jitpack when it is fixed.

**Comment by Aspsine** [comment]
@twiceyuan 
Please update lib version to: 0.0.3.

**Comment by twiceyuan** [comment]
@Aspsine 
好的，感谢 🙏🏼
