### ISSUE TITLE
显示的时候，第一条数据距离顶部有一段距离

### ISSUE THREAD

**Issue by nanchen2251** [Aspsine/IRecyclerView#30]

**Comment by nanchen2251** [comment]
只要一设置分割线就会出现顶部有个两倍间隔的距离。
mRecyclerView.addItemDecoration(new ItemDecoration() {
            @Override
            public void getItemOffsets(Rect outRect, View view, RecyclerView parent, State state) {
                outRect.set(0,0,0,40);
            }
        });

**Comment by Aspsine** [comment]
#4
