### ISSUE TITLE
使用ViewPager+Fragement调用的时候，频繁操作经常出现没办法加载更多

### ISSUE THREAD

**Issue by greenfly555** [Aspsine/IRecyclerView#36]
使用ViewPager+Fragement调用的时候，单独上拉刷新一个栏目下没问题，如果一个栏目没更新完就点下一个栏目，下一个栏目在显示后，上拉到底部有时候没办法显示继续加载或者已经到最后，就是没办法加载了，也上拉不动了，估计是loadMoreFooterView.setStatus(LoadMoreFooterView.Status.THE_END)被共用了

**Comment by Aspsine** [comment]
你应该是ViewPager中的每个fragment中的loadMoreFooterView的状态变量用了同一个。
