### ISSUE TITLE
没有进行任何操作，rv会定时输出下面的日志。。。

### ISSUE THREAD

**Issue by jyh149129** [Aspsine/IRecyclerView#5]
![1111](https://cloud.githubusercontent.com/assets/7726240/14667202/8e371c7e-0710-11e6-94c7-c3e75f835a60.png)
手机放着，没有进行任何操作，但却输出了很多图上显示的信息，有定时任务在跑吗？

**Comment by Aspsine** [comment]
没有定时任务。
如果没有掉用

``` java
iRecyclerView.setRefreshing(true);
```

而直接调用

``` java
iRecyclerView.setRefreshing(false);
```

这句log就会出现。

某些情景下，不需要`iRecyclerView.setRefreshing(true);`，但回调方法中需要调用`iRecyclerView.setRefreshing(false);` 来关闭用户手动刷新。

所以，不用在意这句log。不影响使用。下个版本中我可能会把这个log的level改成warning.而不是error.

**Comment by jyh149129** [comment]
谢谢，显示不显示改log倒不是关键，关键是为什么app不进行任何操作也会一直循环输出这个log信息

**Comment by Aspsine** [comment]
检查代码中调用`iRecyclerView.setRefreshing(false);`的地方，看看是否有递归或者循环, 或者多次调用的操作。
这句log出现的的原理已经做了说明，若不主动调用，这句log是不会打印的。

**Comment by jyh149129** [comment]
谢了，我会再仔细检查app代码调用这个的
